### ISSUE TITLE
Error with tenant scope and db:seed

### ISSUE THREAD

**Issue by ryanengland** [AuraEQ/laravel-multi-tenant#22] opened 2014-11-18 16:49 UTC
Hey! I addes this as a post on the original issue, but didn't know if this should be opened as a separate but, so am posting this as a separate issue too - sorry for the duplicate and please remove whichever one you like.

I seem to be getting the TenantColumnUnknownException issue with db:seed :( Code as below:

In app/database/seeds/DatabaseSeeder.php:

	<?php

	class DatabaseSeeder extends Seeder {

		/**
		 * Run the database seeds.
		 *
		 * @return void
		 */
		public function run()
		{

			Eloquent::unguard();

			TenantScope::disable();
			
			$this->call('AccountsUsersSeeder');

		}

	}

In app/database/seeds/AccountsUsersSeeder.php:

	<?php
	 
	class AccountsUsersSeeder extends Seeder {
	 
		public function run()
		{

			/**
			 * ACCOUNTS DATA
			 */
			Account::create(array(
				'name' 			=> 'XXXXXX',
				'abbreviation' 	=> 'XXXXXX',
				'website'		=> 'XXXXXX',
				'email'			=> 'XXXXXX',
				'logo'			=> 'XXXXXX',
				'address'		=> array('XXXXXX','XXXXXX','XXXXXX','XXXXXXX','XXXXXX','XXXXXX')
			));

			/**
			 * USERS DATA
			 */
			$account_id = DB::table('accounts')
						->select('id')
						->where('name', 'XXXXXX')
						->first()
						->id;
	 
			User::create(array(
				'account_id'=> $account_id,
				'password' 	=> Hash::make('xxxxxx'),
				'email'		=> 'test@test.com',
				'first_name'=> 'User',
				'last_name'	=> 'Name'
			));

		}
	 
	}

Running `php artisan migrate:refresh --force` runs correctly, building the correct tables, etc. Running `php artisan db:seed --force` returns:

	php artisan db:seed --force
	                                                                               
	[AuraIsHere\LaravelMultiTenant\Exceptions\TenantColumnUnknownException]      
	AuraIsHere\LaravelMultiTenant\TenantScope: tenant column "account_id" NOT f  
	ound in tenants scope "[]"                                                   
	                                                                           
	db:seed [--class[="..."]] [--database[="..."]] [--force]

From limited testing, the line that seems to be causing the error is in AccountsUsersSeeder:

	User::create(array(
		'account_id'=> $account_id,
		'password' 	=> Hash::make('xxxxxx'),
		'email'		=> 'test@test.com',
		'first_name'=> 'User',
		'last_name'	=> 'Name'
	));

But `TenantScope::disable()` in DatabaseSeeder.php should have disabled scoping by tenant. Could someone help?

Thanks!

Ryan

**Comment by jbrown8181** [comment] 2015-01-22 15:16
Also having this problem when running tests through Codeception - I have been setting the TenantScope in the before filter, which works well for TenantScope::addTenant(), but not for TenantScope::disable(). 

Searching through the package I understand that with the scope disabled, it will attempt to remove a scope which (in this case) hasn't been set, thus throwing the error. However, I have tried @ryanengland 's approach, which would set a scope to subsequently be removed, but this still hasn't worked for some reason.

I will keep looking through for a solution, but I wonder if anyone else was still having these issues?

**Comment by HipsterJazzbo** [comment] 2015-01-26 21:23
I think this may be caused by the same bug we're digging out in #29. Anyone interested in this, please have a look there and give us your thoughts?

**Comment by HipsterJazzbo** [comment] 2015-01-27 02:32
I'd appreciate if someone would test with this commit (`"aura-is-here/laravel-multi-tenant": "dev-master"`) and report back :)

**Comment by rscafi** [comment] 2015-01-27 13:43
@HipsterJazzbo now using disable() doesn't throws any error, but there's still an issue.
All my tenant columns are being filled with last inserted tenant's id upon seeding, even though I'm providing the correct index for field (it's being ignored/overwritten somehow).

Can you take a look at it?

**Comment by HipsterJazzbo** [comment] 2015-01-27 19:59
So, is this working fine now? Can we close this?

**Comment by jbrown8181** [comment] 2015-01-27 20:50
Great. Tests are running now without setting addTenant before disabling. Thank you!

**Comment by rscafi** [comment] 2015-01-27 21:05
Working like a charm. Thanks!

**Comment by jbrown8181** [comment] 2015-01-27 22:29
Having said that, I am not sure that scopes are being set at all now? I have tested where no TenantScope::disable() has run and TenantScope::addTenant() has been run, but the queries are not scoped. I switched back the old code to test and the query was scoped fine.

**Comment by dieg0v** [comment] 2015-01-27 23:37
On database seeder works for me now without add TenantScope::addTenant() and without TenantScope::disable() too.

Thanks!

**Comment by HipsterJazzbo** [comment] 2015-01-28 00:57
Sweet.

**Closed by HipsterJazzbo** 2015-01-28 00:57 UTC
